apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-poc-deployment-${suffix}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-poc-${suffix}
    spec:
      containers:
      - name: k8s-poc-${suffix}
        image: ehipolito/k8s-poc:1
        ports:
        - containerPort: 8181
          name: k8s-poc-port
