apiVersion: v1
kind: Service
metadata:
  name: k8s-poc-service-${suffix}
spec:
  ports:
  - port: 80
    targetPort:  k8s-poc-port-v1
    protocol: TCP
  selector:
    app: k8s-poc-v1
  type: LoadBalancer